@StoreOrderTracker.Server_HostAddress = http://localhost:5137

POST {{StoreOrderTracker.Server_HostAddress}}/AddOrders
Accept: application/json

{
            "CustomerName": "bob",
            "CustomerPhoneNumber": "1234",
            "Order" : "shirt",
            "AmountDue": "0.00"
}
###
